language: python
python:
  - "3.5"
before_install:
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install -r requirements.txt
  
script:
  - pytest

addons:
  firefox: "latest"
